/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-09-17 15:39:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.home.model.*;

public final class clientlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1505570815620L));
    _jspx_dependants.put("/footer.html", Long.valueOf(1505295415709L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./CSS/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("<h1 class=\"headertxt\">Homeowner Insurance</h1>\r\n");
      out.write("<hr>\r\n");
 String username = (String)request.getSession().getAttribute("username"); 
      out.write("\r\n");
      out.write("<!-- potentially pass this array as context -->\r\n");
      out.write("\r\n");
 if(username!=null||username==""){ 
      out.write("\r\n");
      out.write("<nav class=\"nav\"><a href=\"#\">Home</a> | <a href=\"#\">Get Quote</a> | <a href=\"#\">Retrieve Quote</a>| <a href=\"#\">My Policies</a>| <a href=\"#\">Logout</a></nav>\r\n");
}
      out.write("\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t<div class= \"container\">\r\n");
      out.write("\t\t<div class=\"logintxtsection\">\r\n");
      out.write("\t\t<p class=\"logintxt\">Home insurance, also commonly called hazard insurance or homeowner's insurance is a type of property insurance that covers a private residence, such as a condominium or renters' insurance or home or multiple unit buildings.</p>\r\n");
      out.write("\t\t<p class=\"logintxt\">It is an insurance policy that combines various personal insurance protections, which can include losses occuring to one's home, its contents, loss of use (additional living expenses), or loss of other personal possessions of the homeowner as well as liability insurance for accidents that may happen at the home or at the hands of the homeowner within the policy territory. If a home does not meet the underwriting guidlines of a standard homeowners policy the residence could qualify for a limited coverage dwelling policy.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"loginformsection\">\r\n");
      out.write("\t\t\t<div class=\"stockphoto1\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<form action=\"UserServlet?action=login\" method=\"post\">\r\n");
      out.write("\t\t\t<label>User id</label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"username\"/><br>\r\n");
      out.write("\t\t\t<label>Password</label>\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"password\"/><br>\r\n");
      out.write("\t\t\t<input type=\"submit\" name=\"Login\" value=\"Login\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\tNew User? <a href=\"newUser.jsp\">Register here</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("<div class=\"footer\">\r\n");
      out.write("    <hr>\r\n");
      out.write("    Copyright &copy 2016 Homeownerinsurance.com.All Rights Reserved\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
