/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-09-17 15:40:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.home.model.*;

public final class homeownerInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<title>Home owner information</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./CSS/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

Users user = (Users)session.getAttribute("user");

      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"logintxtsection\">\r\n");
      out.write("\t\t\t<img class=\"stockphoto1\" style=\"width:300px\" alt=\"home\" src=\"http://www.leisepropertyservices.com/wp-content/uploads/2014/12/selling-your-home-cedar-shingle-home11.jpg\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"loginformsection\">\r\n");
      out.write("\t\t\t<form action=\"HomeownerServlet?action=save\" method=\"POST\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"user_id\" value=");
      out.print( user.getUserId() );
      out.write(" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"location_Id\" value=");
      out.print( session.getAttribute("locationId").toString() );
      out.write(" />\r\n");
      out.write("\t\t\t\t<label>First Name<span class=\"asterisk\">*</span></label><br/>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"first_name\"/><br/>\r\n");
      out.write("\t\t\t\t<label>Last Name<span class=\"asterisk\">*</span></label><br/>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"last_name\"/><br/>\r\n");
      out.write("\t\t\t\t<label>Date of Birth<span class=\"asterisk\">*</span></label><br/>\r\n");
      out.write("\t\t\t\t<input type=\"date\" name=\"dob\"/><br/>\r\n");
      out.write("\t\t\t\t<label>Are you retired?<span class=\"asterisk\">*</span></label><br/>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"retired\" value=\"y\"> Yes<br>\r\n");
      out.write("  \t\t\t\t<input type=\"radio\" name=\"retired\" value=\"n\"> No<br>\r\n");
      out.write("\t\t\t\t<label>Social Security Number<span class=\"asterisk\">*</span></label><br/>\r\n");
      out.write("\t\t\t\t<input type=\"number\" name=\"ssn\"/><br/>\r\n");
      out.write("\t\t\t\t<label>Email address<span class=\"asterisk\">*</span></label><br/>\r\n");
      out.write("\t\t\t\t<input type=\"email\" name=\"email_id\"/><br/>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"continue\"/><br/>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
