/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-09-19 01:34:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.home.model.*;

public final class property_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./CSS/style.css\">\r\n");
      out.write("<title>Property Details</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

Users user = (Users)session.getAttribute("user");
String location_id = session.getAttribute("locationId").toString();

      out.write("\r\n");
      out.write("<form action=\"PropertyServlet?action=save\" method=\"post\">\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<input type=\"hidden\" name=\"location_id\" value=\"");
      out.print(location_id);
      out.write("\"/>\r\n");
      out.write("        <input type=\"hidden\" name=\"user_id\" value=\"");
      out.print(user.getUserId());
      out.write("\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label>What is the market value of your home?</label><br/>\r\n");
      out.write("\t\t$<input type=\"text\" name=\"market_value\"><br/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label>What year was your home originally built?</label><br/>\r\n");
      out.write("\t\t<input type=\"text\" name=\"year_built\"><br/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label>Square footage</label><br/>\r\n");
      out.write("\t\t<input type=\"text\" name=\"sqft\">sqft<br/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label>Dwelling Style</label><br/>\r\n");
      out.write("\t\t<select name=\"dwell_style\">\r\n");
      out.write("\t\t  <option value=\"1\">1 Story</option>\r\n");
      out.write("\t\t  <option value=\"1.5\">1.5 Story</option>\r\n");
      out.write("\t\t  <option value=\"2\">2 Story</option>\r\n");
      out.write("\t\t  <option value=\"2.5\">2.5 Story</option>\r\n");
      out.write("\t\t  <option value=\"2.5\">3 Story</option>\r\n");
      out.write("\t\t</select><br/>\r\n");
      out.write("\t\t\r\n");
      out.write("        <label>Roof Material</label><br/>\r\n");
      out.write("\t\t<select name=\"roof_material\">\r\n");
      out.write("\t\t  <option value=\"Concrete\">Concrete</option>\r\n");
      out.write("\t\t  <option value=\"Clay\">Clay</option>\r\n");
      out.write("\t\t  <option value=\"Rubber\">Rubber</option>\r\n");
      out.write("\t\t  <option value=\"Steel\">Steel</option>\r\n");
      out.write("\t\t  <option value=\"Tin\">Tin</option>\r\n");
      out.write("\t\t  <option value=\"Wood\">Wood</option>\r\n");
      out.write("\t\t</select><br/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label>Type of Garage</label><br/>\r\n");
      out.write("\t\t<select name=\"garage_type\">\r\n");
      out.write("\t\t  <option value=\"Attached\">Attached</option>\r\n");
      out.write("\t\t  <option value=\"Detached\">Detached</option>\r\n");
      out.write("\t\t  <option value=\"Basement\">Basement</option>\r\n");
      out.write("\t\t  <option value=\"Built-In\">Built-In</option>\r\n");
      out.write("\t\t  <option value=\"None\">None</option><br/>\r\n");
      out.write("\t\t</select><br/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label>Full Baths</label><br/>\r\n");
      out.write("\t\t<select name=\"num_full_bath\">\r\n");
      out.write("\t\t  <option value=\"0\">0</option>\r\n");
      out.write("\t\t  <option value=\"1\">1</option>\r\n");
      out.write("\t\t  <option value=\"2\">2</option>\r\n");
      out.write("\t\t  <option value=\"3\">3</option>\r\n");
      out.write("\t\t  <option value=\"more\">More</option>\r\n");
      out.write("\t\t</select><br/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label>Half-Baths</label><br/>\r\n");
      out.write("\t\t<select name=\"num_half_bath\">\r\n");
      out.write("\t\t  <option value=\"0\">0</option>\r\n");
      out.write("\t\t  <option value=\"1\">1</option>\r\n");
      out.write("\t\t  <option value=\"2\">2</option>\r\n");
      out.write("\t\t  <option value=\"3\">3</option>\r\n");
      out.write("\t\t  <option value=\"more\">More</option>\r\n");
      out.write("\t\t</select><br/>\r\n");
      out.write("\t\t<label>Do you have a pool</label><br/>\r\n");
      out.write("\t\t<input type=\"radio\" name=\"has_pool\" value=\"Yes\">Yes<br>\r\n");
      out.write("        <input type=\"radio\" name=\"has_pool\" value=\"No\">No<br>\r\n");
      out.write("        \r\n");
      out.write("        <input type=\"submit\" name=\"submit\" value=\"Continue\"><br>\r\n");
      out.write("\t\t\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
