/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-09-19 01:34:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.home.model.*;
import com.home.bo.*;

public final class quotesummary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Quote Summary</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./CSS/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	int location_id = Integer.parseInt(session.getAttribute("locationId").toString());
	Users user = (Users) session.getAttribute("user");
	int user_id = user.getUserId();
	Homeowners homeowner = null;
	HomeownerBO homeownerBO = new HomeownerBO();
	homeowner = homeownerBO.getOneHomeOwner(user_id, location_id);

	PropertyDetails property = null;
	PropertyDetailBO propertyBO = new PropertyDetailBO();
	property = propertyBO.getOneLocationId(user_id, location_id);

	LocationAddress location = null;
	LocationAddressBO locationBO = new LocationAddressBO();
	location = locationBO.getOneLocationAddress(user_id, location_id);
	
	QuoteDetails quote = null;
	QuoteDetailBO quoteBO = new QuoteDetailBO();
	quote = quoteBO.getQuoteDetails(user_id);


      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\tuser id");
      out.print(user_id);
      out.write("\r\n");
      out.write("\tlocation id\r\n");
      out.write("\t");
      out.print(location_id);
      out.write("\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<h1>Quote Summary</h1>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t\t<h3>\r\n");
      out.write("\t\t\tMonthly Premium <span class=\"asterisk\">$");
      out.print(quote.getMonthlyPremium());
      out.write("</span>\r\n");
      out.write("\t\t</h3>\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<form method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" name=\"Buy Quote\" value=\"continue\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div class=\"logintxtsection\">\r\n");
      out.write("\t\t\t\t<h2>Location Details</h2>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Quote Id</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(location.getLocationId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Residence Type</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(location.getResidenceType());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Address Line 1</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(location.getAddressLine1());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Address Line 2</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(location.getAddressLine2());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>City</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(location.getCity());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>State</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(location.getState());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Zip</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(location.getZip());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Residence Use</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(location.getResidenceUse());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<hr />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h2>Property Details</h2>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Market Value</th>\r\n");
      out.write("\t\t\t\t\t\t<td>$");
      out.print(property.getMarketValue());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Year Built</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(property.getYearBuilt());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Square Footage</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(property.getSqft());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Dwelling Style</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(property.getDwellStyle());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Roof Material</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(property.getRoofMaterial());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Garage Type</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(property.getGarageType());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Number of Full Baths 1</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(property.getNumFullBath());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Number of Half Baths 1</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(property.getNumHalfBath());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Has Swimming Pool?</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(property.getHasPool());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"loginformsection\">\r\n");
      out.write("\t\t\t\t<h2>Homeowner Details</h2>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>First Name</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(homeowner.getFirstName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Last Name</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(homeowner.getLastName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Date of Birth</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(homeowner.getDOB());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Is Retired?</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(homeowner.getRetired());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Social Security Number</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(homeowner.getSSN());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Email Address</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(homeowner.getEmailId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t<h2>Coverage Details</h2>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Monthly Premium</th>\r\n");
      out.write("\t\t\t\t\t\t<td>$");
      out.print(quote.getMonthlyPremium());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Dwelling Coverage</th>\r\n");
      out.write("\t\t\t\t\t\t<td>$");
      out.print(quote.getDwellingCoverage());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Detached Structure</th>\r\n");
      out.write("\t\t\t\t\t\t<td>$");
      out.print(quote.getDetachedStructures());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Personal Property</th>\r\n");
      out.write("\t\t\t\t\t\t<td>$");
      out.print(quote.getPersonalProperty());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Additional living expense</th>\r\n");
      out.write("\t\t\t\t\t\t<td>$");
      out.print(quote.getLivingExpense());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Medical Expense</th>\r\n");
      out.write("\t\t\t\t\t\t<td>$");
      out.print(quote.getMedExp());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Deductible</th>\r\n");
      out.write("\t\t\t\t\t\t<td>$");
      out.print(quote.getDeductible());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<form method=\"post\" action=\"\">\r\n");
      out.write("\t\t<input type=\"submit\" name=\"Buy Quote\" value=\"continue\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
